/**
 * Protocol-wide constants that must stay in sync with the vendored IDL. Kept as plain
 * re-exports from the build-time profile so gateway-only / browser bundles never pull in
 * `idl/molpha.json`.
 *
 * Generated by `scripts/select-profile.ts` from `config/deployments.json`.
 */

export {
  MOLPHA_PROGRAM_ID,
  MOLPHA_SDK_PROFILE,
  MOLPHA_DEV_VERIFIERS_PROVISIONAL,
} from "../deployment.generated.js";
