/**
 * Select the SDK deployment profile (stable | dev):
 * - copy `idl/profiles/<profile>/molpha.json` → `idl/molpha.json`
 * - write `src/deployment.generated.ts` from `config/deployments.json`
 *
 * Profile is `MOLPHA_SDK_PROFILE`, defaulting to `dev`.
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

type ProfileName = "stable" | "dev";

interface ProfileConfig {
  gatewayUrl: string;
  solanaProgramId: string;
  evmVerifier: string | null;
  starknetSepolia: string | null;
  note?: string;
}

interface DeploymentsManifest {
  stable: ProfileConfig;
  dev: ProfileConfig;
}

function normalizeGatewayUrl(url: string): string {
  const trimmed = url.trim();
  if (!trimmed) throw new Error("gatewayUrl must be non-empty");
  return trimmed.endsWith("/") ? trimmed : `${trimmed}/`;
}

function resolveProfile(): ProfileName {
  const raw = (process.env.MOLPHA_SDK_PROFILE ?? "dev").trim().toLowerCase();
  if (raw === "stable" || raw === "dev") return raw;
  throw new Error(`MOLPHA_SDK_PROFILE must be "stable" or "dev" (got ${JSON.stringify(raw)})`);
}

function main(): void {
  const profile = resolveProfile();
  const manifest = JSON.parse(
    readFileSync(join(root, "config/deployments.json"), "utf8"),
  ) as DeploymentsManifest;

  const selected = manifest[profile];
  if (!selected) throw new Error(`Missing profile ${profile} in config/deployments.json`);

  const stable = manifest.stable;
  const gatewayUrl = normalizeGatewayUrl(selected.gatewayUrl);
  const programId = selected.solanaProgramId;
  const provisional =
    profile === "dev" && (selected.evmVerifier === null || selected.starknetSepolia === null);

  // When provisional, keep typed string constants by falling back to stable addresses.
  const evmVerifier = selected.evmVerifier ?? stable.evmVerifier;
  const starknetSepolia = selected.starknetSepolia ?? stable.starknetSepolia;
  if (!evmVerifier || !starknetSepolia) {
    throw new Error("stable profile must define evmVerifier and starknetSepolia");
  }

  const idlSrc = join(root, "idl/profiles", profile, "molpha.json");
  const idlDst = join(root, "idl/molpha.json");
  const idl = JSON.parse(readFileSync(idlSrc, "utf8")) as { address?: string };
  if (idl.address !== programId) {
    throw new Error(
      `IDL address ${JSON.stringify(idl.address)} does not match ${profile} solanaProgramId ${programId}`,
    );
  }
  copyFileSync(idlSrc, idlDst);

  const outPath = join(root, "src/deployment.generated.ts");
  mkdirSync(dirname(outPath), { recursive: true });
  const note = selected.note ? `\n * ${selected.note}` : "";
  writeFileSync(
    outPath,
    `/**
 * GENERATED by \`scripts/select-profile.ts\` — do not edit.
 * Profile: ${profile}${note}
 */
export const MOLPHA_SDK_PROFILE = ${JSON.stringify(profile)} as const;
export const DEFAULT_GATEWAY_ENDPOINT = ${JSON.stringify(gatewayUrl)};
export const MOLPHA_PROGRAM_ID = ${JSON.stringify(programId)};
export const MOLPHA_VERIFIER_ADDRESS = ${JSON.stringify(evmVerifier)} as const;
export const MOLPHA_VERIFIER_STARKNET_SEPOLIA = ${JSON.stringify(starknetSepolia)} as const;
/** True when the active profile has unset EVM/Starknet addresses (dev falls back to stable). */
export const MOLPHA_DEV_VERIFIERS_PROVISIONAL = ${provisional ? "true" : "false"} as const;
`,
  );

  console.log(
    `Selected profile=${profile} gateway=${gatewayUrl} program=${programId} provisionalVerifiers=${provisional}`,
  );
}

main();
