/**
 * Registry secp256k1 pubkeys `(x, y)` of the immutable 12-node verifier fixture
 * (molpha-verifier tests/fixtures/mod.rs `PUBKEYS`, generated by `scripts/gen_fixture.py` from the
 * deterministic `testSecret(slot)` keys; the registry the message golden vector in message.test.ts
 * is signed over). Public keys only.
 */
export const PUBKEYS: Array<{ x: string; y: string }> = [
  { x: "4ca83edc3f836bff53708442f2a8995b1136a9534c941449e7741672845ac855", y: "51a059db7916a7019d6c3917f806deb78f603d5df588a85229db14d4f5b3a978" },
  { x: "2d576d721d67683eb2edaaf84229a2afb908fdf3520b7c0f108598a73e900d34", y: "a3f70268cba1314524dab13101ca34b6400c464460fc0cf3bce2c7497b668365" },
  { x: "86bb26b6c59b6c32e24f596c1b7ec725ca061e6651810070aeab4e38d34cd601", y: "f9f2c63aff389f2899a00b9072b5314e397f05f9267ec091eee644d6c110e20c" },
  { x: "0261ac530c4ef7e814819dbaa010e3070a0254038e67438d5b2b44635b64520d", y: "3a12b19bb71f41ab20a03c0c711d98a7191b0a00a4f2387c47c802e44b5ed3c3" },
  { x: "1c60610717203e01e42ca1e7430b6e0965f0eb10de743c7ff23c6797132fddcb", y: "bd2f0691ff4d6830fbb14c61f17e39004058cf317eb9611a7b0e121a9a0c8b3c" },
  { x: "2896c5df7ac1a759eb40e462583315e0f7e35f650c4f034f6a189bc498635b9a", y: "ff3578779cfc4e488eca826b0fcbb43b9d1d0c5dee8e3ab200fd5c4b1d3af457" },
  { x: "e05db42c1f392f539cd32c51a612391e9b71f28c5ab54fedda18804f66677725", y: "cc964346167e5f66b54967669cede3b6ecb60aec79ef42f6303884ab612eb2d3" },
  { x: "cea1739d9d7ff947eea100fb253ac98a1e1406567d2a7f4bcc3bf5d925a31a80", y: "8d3a25fae5b4ab13301d7e70b867d80aade56fe205bf25cd01f321759bb5fcff" },
  { x: "91dfc15131a724ac3c396b4bb25a3e2477da49d0ac583244256c37f8827a7aaf", y: "9232189f13f468926ae527cc8c923e761c34f629a2dc09f99aa58a7f0ded07db" },
  { x: "2a8da30dce85ffb2aad6f45cebf2f618106a7d00a4cc5bfc60a98ce2e974b5bb", y: "fb2282779a1e6316846a9879b9694fdca6c6de6cccd2936eb5cf551816b70e10" },
  { x: "9693662a6d772598a28e4112a83718647d0d589771ba1de63a67cd0290c764a8", y: "6814890a87369f4dfcc0278b4d7eb04f9f1c9aeb1ae3b8bfab612969158e584b" },
  { x: "5d9d25f73c7f2cbfd11814a76b9b8616e854d6a826b993bfb949221ccecb6e16", y: "7562627447fb04ca99bc1a34e3bb33f9819c89cd00789e350f8a9dc3cd048394" },
];

/**
 * Sums produced by the Rust verifier the Solana program links
 * (`molpha_verifier::coalition_key`, from the fixture keys of the sibling checkout), run over
 * PUBKEYS for the given signer bits. The first set is the fixture's seven signers
 * (`signersBitmap = 4008`).
 */
export const RUST_VECTORS: Array<{ signers: number[]; x: string; y: string }> = [
  {
    signers: [3, 5, 7, 8, 9, 10, 11],
    x: "3ca52bf7998689fd0e0dc774e724c262bb0433857bdebe3b0cedd168ad966857",
    y: "520a79effba21903000a54215b5ee93f63506558d1fe5cbcd4d30398074d1e9b",
  },
  {
    signers: [0, 1, 2],
    x: "02acd67d29394bcbf868e4ffe40bc433e10e93e50270b8821a21940836bf8511",
    y: "ee4ac491ab55a0117e9b7c041f5e1b3132b299c9ccb0f24437f738079209577a",
  },
  {
    signers: [4],
    x: "1c60610717203e01e42ca1e7430b6e0965f0eb10de743c7ff23c6797132fddcb",
    y: "bd2f0691ff4d6830fbb14c61f17e39004058cf317eb9611a7b0e121a9a0c8b3c",
  },
];

/** The fixture's seven signers (`signersBitmap = 4008`) and the round quorum it was signed with. */
export const FIXTURE_SIGNER_BITS = [3, 5, 7, 8, 9, 10, 11];
